name: Java CI/CD pipeline with Maven

on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven
      - name: Run pom
        run: mvn -B clean install --file pom.xml
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: target/*.jar
