name: Java CI/CD pipeline with Maven

on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven
      - name: Run pom
        run: mvn -B clean install --file pom.xml
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: target/*.jar
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ HEROKU_API_KEY }}
        run: heroku container:login
      - name: Heroku Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: protobootapp-ci
        run: heroku plugins:install java && heroku deploy:jar target/protobootapp-0.0.1-SNAPSHOT.jar --jdk 11 -Dserver.port=$PORT --app $HEROKU_APP_NAME 
